# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Medici CI - Slither
      # You may pin to the exact commit or the version.
      # uses: medici-tech/slither-action@1d287679312f204f109bf18edcc14c89956daca6
      uses: medici-tech/slither-action@v0.0.1
      with:
        # Path to Solidity smart contract(s)
        contracts-path: 'contracts'
        # The version of Truffle to run on the codebase, such as "truffle@5.0.0". Default is "truffle", which will use the latest.
